// Verilog code generated by IPXactVisualizer
// Project: Tiger
// Module: lsd
// Version: 1.0
// Generated on: 2026-06-16 16:02:27

module lsd (
    // input Ports
    input   clk,
    input   rst,
    input   data,
    // output Ports
    output  data 1,
    output  data2
);

endmodule