// Verilog code generated by IPXactVisualizer
// Project: test
// Module: test
// Version: 1.0
// Generated on: 2026-04-30 17:44:34

module test (
    // input Ports
    input  clk,
    input  rst,
    // output Ports
    output reg  data_out
);




endmodule