// Verilog code generated by IPXactVisualizer
// Project: Tiger
// Module: noc
// Version: 1.0
// Generated on: 2026-04-06 22:32:01

module noc (
    // input Ports
    input  clk,
    input  rst
    // output Ports
    output reg  data_out,
    output reg  data0,
    output reg  data1,
    output reg  OutPort
);


    // Internal wires
    wire  u_QSPI_0_clk;
    wire  u_QSPI_0_rst;
    wire [31:0] u_QSPI_0_data_in;
    wire [31:0] u_QSPI_0_data_out;
    wire  u_QSPI_1_clk;
    wire  u_QSPI_1_rst;
    wire [31:0] u_QSPI_1_data_in;
    wire [31:0] u_QSPI_1_data_out;
    wire  u_QSPI_2_clk;
    wire  u_QSPI_2_rst;
    wire [31:0] u_QSPI_2_data_in;
    wire [31:0] u_QSPI_2_data_out;



    // Component instances
    QSPI u_QSPI_0 (
        .clk(u_QSPI_0_clk),
        .rst(u_QSPI_0_rst),
        .data_in(u_QSPI_0_data_in),
        .data_out(u_QSPI_0_data_out)

    );
    QSPI u_QSPI_1 (
        .clk(u_QSPI_1_clk),
        .rst(u_QSPI_1_rst),
        .data_in(u_QSPI_1_data_in),
        .data_out(u_QSPI_1_data_out)

    );
    QSPI u_QSPI_2 (
        .clk(u_QSPI_2_clk),
        .rst(u_QSPI_2_rst),
        .data_in(u_QSPI_2_data_in),
        .data_out(u_QSPI_2_data_out)

    );



    // Connections
    assign u_QSPI_2_data_in = u_QSPI_0_data_out;
    assign u_QSPI_1_data_in = u_QSPI_0_data_out;
    assign OutPort = u_QSPI_1_data_out;
    assign data_out = u_QSPI_2_data_out;


endmodule